server:
  port: 8080

spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
      auto-index-creation: true  # @Indexed 자동 생성 추천

jwt:
  secret: ${JWT_SECRET:jwt-secret-key-jwt-secret-key-jwt-secret-key}
  expiration: ${JWT_EXPIRATION:3600000}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: debug
